AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hermes

  SAM Template for hermes

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HermesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hermes/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Hermes:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hermes
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HermesApi:
    Description: "API Gateway endpoint URL for Prod stage for Hermes function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hermes/"
  HermesFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HermesFunction.Arn
  HermesFunctionIamRole:
    Description: "Implicit IAM Role created for Hermes
     function"
    Value: !GetAtt HermesFunctionRole.Arn
